# Signatories
<!-- 
This section provides the ISC with a view of the support received from the community for a proposal. Acceptance isn't predicated on popularity but community acceptance is important.  Willingness to accept outside input is also a good marker for project delivery. 

An optional section would be for R-Core signatories where changes to R are proposed.
-->

The **Project team** lists the core members of the work, who will be
instrumental in progress and completion of the project. Signatories
are listed by alphabetical order.  **Note: R packages to which people
contributed are indicated within brackets.**


## Project team
<!-- 
Who are the people responsible for actually delivering the project if the proposal gets accepted and are already signed up and rearing to go?
-->

  * **Mathieu Basille**, Assistant Professor at the University of
    Florida, USA [`adehabitatHS`, `hab`, `rpostgis`, `rpostgisLT`]
  * **Matt Boone**, Data Scientist at the University of Florida, USA
    [`refsplitr`]
  * **Clément Calenge**, Statistical Analyst at the *Office national
    de la chasse et de la faune sauvage*, France [`adehabitatMA`,
    `adehabitatHR`, `adehabitatHS`, `adehabitatLT`]
  * **Rocío Joo**, Postdoctoral Associate at the University of
    Florida, USA
  * **Emiel van Loon**, Assistant Professor at the University of
    Amsterdam, the Netherlands [`zoon`, `RNCEP`].


<!-- ## Contributors -->
<!-- 
Who are the people who have actively helped with this proposal but won't necessarily be on the core project team later?
-->

<!-- ## Consulted -->
<!-- 
Who has been given the opportunity to provide feedback on the proposal? This should include any R Consortium & ISC members who the proposal has been discussed with.
-->

