# Project plan

## Start-up phase
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->

The `sftraj` package is meant to be a cornerstone for the development
of a more cohesive Movement community in R. The first stage of the
work, which just started, will deliver solid technical foundations for
trajectories in R. Our project has already been received very
positively on Twitter, which we use to channel our communication. Two
blog posts (https://mablab.org/post/sftraj-intro/ and
https://mablab.org/post/sftraj-plan/) finally explain what we are
doing, and why we need feedback from the community. Interestingly, in
a very short period of time, we already received the perspective on
`sftraj` from developers of 4 tracking packages (`amt`, `crawl`,
`spatsoc`, and `wildlifeDI`), which comes in addition to our early
discussions with 5 developers from three other tracking packages
(`VTrack`, `moveHMM` and `momentuHMM`). Altogether, feedback received
only confirms the need for a central trajectory package in R.


## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

Progress will focus on the delivery of four products of increasing
complexity. They will be addressed one by one, as they all build on
top of each other:

* **Vignette of the package** [month 1]: Writing a vignette will
  provide a reproducible tutorial which will guide through the use of
  `sftraj`. A well-written vignette is now essential for users to get
  started and see the benefits of using a package.
* **Submission to CRAN** [month 1]: During the first stage of the
  work, `sftraj` will become full-featured and installable from
  GitHub. In this second stage, we will ensure that the package is
  ready for CRAN and finally submit it there. Publication on CRAN will
  allow for easy installation on any computer, as well as enabling the
  dependency system of R packages, which are both mandatory for broad
  adoption.
* **Submission to rOpenSci** [month 2]: After the package has been
  submitted to CRAN, we will go one step further and actually prepare
  it for rOpenSci. rOpenSci emphasizes (and basically enforces) a
  package's quality, fit, documentation, and clarity. `sftraj` would
  fit in the special category "geospatial data". Becoming the first
  official rOpenSci tracking package (none of the 57 existing tracking
  packages are currently on rOpenSci) would give the package an extra
  exposure, and guarantee its overall usefulness and usability.
* **Submission of a companion manuscript to the R Journal** [month
  3–4]: Finally, as the quality of `sftraj` increases with the
  previous steps, we will work on a manuscript aimed at developers to
  provide the rationale behind development decisions for the package,
  and detail its implementation. In practice, this manuscript will
  provide package developers the necessary information for other
  packages to be able to rely on classes from `sftraj`.


## Other aspects
<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->

While the work on `sftraj` will happen completely in the open, we will
keep communicating on our progress, directly on Twitter as well as
with more detailed blog posts on https://mablab.org/. We will watch
for feedback, notably through the GitHub repository, which will remain
constantly open.

In parallel, we will use scientific conferences (which we already
planned to attend, using other funding) to introduce `sftraj` and
present our work, such as useR! 2020 (which will be held in St. Louis,
Missouri in July 2020), the International Statistical Ecology
Conference (ISEC, which will be held in Sydney Australia, in June
2020), or Moving2Gather (which will be held in Rennes, France in March
2020).
